# Generated by Django 4.2 on 2023-04-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'PLACE', 'verbose_name_plural': 'PLACES'},
        ),
    ]
