# Generated by Django 4.2 on 2023-04-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
