# Generated by Django 4.2 on 2023-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='ID места'),
        ),
    ]
