# Generated by Django 4.2 on 2023-04-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_options_place_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='content',
        ),
    ]
