# Generated by Django 4.2 on 2023-04-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_remove_place_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='long_description',
            new_name='long_description1',
        ),
    ]
