# Generated by Django 4.2 on 2023-04-13 11:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_rename_long_description_place_long_description1'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(default='', verbose_name='Полное описание'),
            preserve_default=False,
        ),
    ]
