# Generated by Django 4.2 on 2023-04-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_place_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='long_description1',
        ),
    ]
