# Generated by Django 4.2 on 2023-04-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_image_image_alter_place_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('id', 'place', 'image')},
        ),
    ]
