# Generated by Django 4.2 on 2023-04-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_alter_place_lat_alter_place_lon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_number', 'place'], 'verbose_name': 'КАРТНКА', 'verbose_name_plural': 'КАРТИНКИ'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'МЕСТО', 'verbose_name_plural': 'МЕСТА'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
